// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2iJsuczN7dJlBGdNkiVSQyNZfsMDpNk',
    appId: '1:309527302341:web:bfc5c22f9f8198abc6e0ac',
    messagingSenderId: '309527302341',
    projectId: 'parchi-cd216',
    authDomain: 'parchi-cd216.firebaseapp.com',
    storageBucket: 'parchi-cd216.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23s3xLf-3-khNnamusoGosu1v3k1V7DI',
    appId: '1:309527302341:android:0b461d3bc7ebfa61c6e0ac',
    messagingSenderId: '309527302341',
    projectId: 'parchi-cd216',
    storageBucket: 'parchi-cd216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28FNQsiaMnLyTA7pqq9xWf2OXRiZ8Cro',
    appId: '1:309527302341:ios:3016bdef3eb223c0c6e0ac',
    messagingSenderId: '309527302341',
    projectId: 'parchi-cd216',
    storageBucket: 'parchi-cd216.appspot.com',
    iosBundleId: 'com.example.parchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm2iJsuczN7dJlBGdNkiVSQyNZfsMDpNk',
    appId: '1:309527302341:web:06645356e4f0a4a2c6e0ac',
    messagingSenderId: '309527302341',
    projectId: 'parchi-cd216',
    authDomain: 'parchi-cd216.firebaseapp.com',
    storageBucket: 'parchi-cd216.appspot.com',
  );
}
